CREATE TABLE transferencias (
    id  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jogador_id bigint NOT NULL,
    time_id bigint NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    data DATE NOT NULL
);